db:
  host: ${oc.env:DB_HOST,localhost}
  port: ${oc.env:DB_PORT,5432}
  database: ${oc.env:DB_NAME,small_etl}
  user: ${oc.env:DB_USER,postgres}
  password: ${oc.env:DB_PASSWORD,postgres}
  url: postgresql://${db.user}:${db.password}@${db.host}:${db.port}/${db.database}
